package com.example.networkingapp.util

val DATA_USERS = "Users"
val DATA_NAME = "name"
val DATA_PROFESSION = "profession"
val DATA_IMAGE_URL = "imageUrl"
val GOALS_HIRE_EMPLOYEES = "Hire employees"
val GOALS_LOOKING_FOR_A_JOB = "Looking for a job"
val GOALS_FIND_COFOUNDERS = "Find Co-Founders"
val GOALS_INVEST_IN_PROJECTS = "Invest in projects"
val GOALS_FIND_INVESTORS = "Find investors"
val GOALS_GROW_MY_BUSINESS = "Grow my business"
val GOALS_HIRE_FREELANCERS = "Hire freelancers"
val GOALS_FIND_FREELANCE_JOBS = "Find freelance jobs"
val GOALS_FIND_MENTORS = "Find mentors"
val GOALS_MENTOR_OTHERS = "Mentor others"
val GOALS_MAKE_NEW_FRIENDS = "Make new friends"
val GOALS_EXPLORE_IDEAS = "Explore ideas"